### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by limelect** [ApocalypseCodingGroup/ApocalypticCards#1]
How to use?
Plz make an explanation how to use?
Also some source are missing

Downloads\RamboSessionIDGen\VCL_RamboSessionIDGen.dproj  ???
May be more??

**Comment by checkdigits** [comment]
You need to watch the YouTube stream.  This is an on-going project and it's not finished yet.

Stream is here: https://www.youtube.com/channel/UCnmItkCyRDqSqq7cKazvxzg/videos
