### ISSUE TITLE
Could we have a linux server binary to test locally?

### ISSUE THREAD

**Issue by gcarreno** [ApocalypseCodingGroup/ApocalypticCards#5]
Hey guys,

Would it possible to, either, include the latest linux server bin with a commit, or have it under release assets?

Many thanks,
Gus

P.S: I'll try and do a Lazarus client.

**Comment by chapmanworld** [comment]
Sure thing, will drop it in the repo on todays stream.

**Comment by gcarreno** [comment]
Thanks!!
